### ISSUE TITLE
exception while stopping daemon

### ISSUE THREAD

**Issue by ggmartins** [noise-lab/netmicroscope-daemon#6]
```
2021-01-01T23:02:34.736 ERROR {diagnostic_utils} [log_exception_func_wrap] Wrapped func exited with exception. Caller's stack:
Traceback (most recent call last):
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1295, in _produce
    super(_AsyncSSLTransport, self)._produce()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1295, in _produce
    super(_AsyncSSLTransport, self)._produce()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2021-01-01T23:02:34.736 INFO {io_services_utils} [_initiate_abort] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 36664), raddr=('127.0.0.1', )>
2021-01-01T23:02:34.736 ERROR {channel} [_on_unexpected_frame] Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.ed7d9910759c4e24ba338872cd3b9ebb'])>"])>
2021-01-01T23:02:34.736 INFO {io_services_utils} [_deactivate] Deactivating transport: state=1; <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 36664), raddr=('127.0.0.1', )>
2021-01-01T23:02:34.736 INFO {channel} [close] Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f4700d85820> params=<ConnectionParameters host= port= virtual_host=/ ssl=True>>>
2021-01-01T23:02:34.737 ERROR {base_connection} [_proto_connection_lost] connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2021-01-01T23:02:34.737 INFO {connection} [_on_stream_terminated] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=None
2021-01-01T23:02:34.737 INFO {connection} [_on_stream_terminated] Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2021-01-01T23:02:34.737 INFO {io_services_utils} [_close_and_finalize] Closing transport socket and unlinking: state=2; <ssl.SSLSocket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 36664), raddr=('127.0.0.1', )>
2021-01-01T23:02:34.737 ERROR {blocking_connection} [_flush_output] Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2021-01-01T23:02:34.737 WARNING {appmonitor} [process_mq_ta] rabbimq SSL channel terminated
```

**Comment by ggmartins** [comment]
Traceback (most recent call last):
  File "/home//nm/netmicroscope-daemon/appmonitor/appmonitor.py", line 481, in process_mq_ta
    channel.start_consuming()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 147, in value
    assert self._ready, '_CallbackResult was not set'
AssertionError: _CallbackResult was not set

**Comment by ggmartins** [comment]
2021-02-14T09:36:24.194 ERROR {blocking_connection} [_flush_output] Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2021-02-14T09:36:24.214 INFO {appmonitor} [run] MAIN: listener join
2021-02-14T09:36:24.305 INFO {appmonitor} [influxdb_updater_thread] Other-ASUSTek_Computer_Inc_64 {'KbpsDw': 13.9828125, 'KbpsUp': 9.9, 'TsEnd': 1613316983, 'Domain': 'wss-primary.slack.com', 'SIP': '18.211.'}
2021-02-14T09:36:24.305 INFO {appmonitor} [influxdb_updater_thread] Unknown-ASUSTek_Computer_Inc_64 {'KbpsDw': 0.578125, 'KbpsUp': 0.0953125, 'TsEnd': 1613316983, 'Domain': '', 'SIP': '162.159.'}
2021-02-14T09:36:24.305 INFO {appmonitor} [influxdb_updater_thread] Other-NVIDIA_Corporation_c9 {'KbpsDw': 0.3078125, 'KbpsUp': 21.44375, 'TsEnd': 1613316983, 'Domain': '', 'SIP': ''}
2021-02-14T09:36:24.317 INFO {appmonitor} [influxdb_updater_thread] OK
2021-02-14T09:36:26.295 INFO {nmd} [main_thread] Exiting...
2021-02-14T09:36:27.254 ERROR {appmonitor} [process_mq_ta] process_mq_ta: <class 'AttributeError'> appmonitor.py 481 'NoneType' object has no attribute 'clear'

**Comment by ggmartins** [comment]
INFO: appmonitor Stopping with args Namespace(callback=<function daemon_stop at 0x7fe464a750d0>)
Traceback (most recent call last):
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1198, in _on_socket_writable
    self._ssl_writable_action()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1295, in _produce
    super(_AsyncSSLTransport, self)._produce()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 819, in _produce
    num_bytes_sent = self._sigint_safe_send(self._sock,
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
  File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home//nm/netmicroscope-daemon/appmonitor/appmonitor.py", line 481, in process_mq_ta
    channel.start_consuming()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/select_connection.py", line 1200, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/select_connection.py", line 904, in _dispatch_fd_events
    handler(fileno, events)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 391, in _on_reader_writer_fd_events
    callbacks.writer()
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 1200, in _on_socket_writable
    self._initiate_abort(error)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/diagnostic_utils.py", line 53, in log_exception_func_wrap
    return func(*args, **kwargs)
  File "/home//nm/netmicroscope-daemon/venv/lib/python3.8/site-packages/pika/adapters/utils/io_services_utils.py", line 935, in _initiate_abort
    assert self._state == self._STATE_ABORTED_BY_USER, (
AssertionError: ('_AsyncTransportBase._initate_abort() expected _STATE_ABORTED_BY_USER', 2)

**Comment by fqlx** [comment]
```
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)
```
This is coming from OpenSSL 1.1.1g

**Comment by jayantkotie** [comment]
> ```
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)
> ```
> 
> This is coming from OpenSSL 1.1.1g

I got this same error 
File "/usr/local/lib/python3.8/ssl.py", line 1173, in send
return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2472)

how do i solve it???
